"""add reports

Revision ID: 7af5b108dd2f
Revises: 34a5655d4a94
Create Date: 2026-07-17 13:27:52.900650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af5b108dd2f'
down_revision = '34a5655d4a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_item_id', sa.Integer(), nullable=True),
    sa.Column('reported_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('\n            (\n                reported_item_id IS NOT NULL\n                AND reported_user_id IS NULL\n            )\n            OR\n            (\n                reported_item_id IS NULL\n                AND reported_user_id IS NOT NULL\n            )\n            ', name='ck_report_exactly_one_target'),
    sa.CheckConstraint('\n            reported_user_id IS NULL\n            OR reporter_id != reported_user_id\n            ', name='ck_report_cannot_report_self'),
    sa.ForeignKeyConstraint(['reported_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_status_created_at', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_status_created_at')

    op.drop_table('reports')
    # ### end Alembic commands ###
