"""Add student verification workflow fields

Revision ID: e10968e88130
Revises: 0050fb27d2c6
Create Date: 2026-07-27 14:52:34.742051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10968e88130'
down_revision = '0050fb27d2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_document_public_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_document_format', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('verification_rejection_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('verification_submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_users_verification_reviewed_by_id_users",
            "users",
            ["verification_reviewed_by_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_users_verification_reviewed_by_id_users",
            type_="foreignkey",
        )
        batch_op.drop_column('verification_reviewed_by_id')
        batch_op.drop_column('verification_reviewed_at')
        batch_op.drop_column('verification_submitted_at')
        batch_op.drop_column('verification_rejection_reason')
        batch_op.drop_column('verification_document_format')
        batch_op.drop_column('verification_document_public_id')

    # ### end Alembic commands ###
